# Generated by Django 4.1.7 on 2023-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=4),
        ),
    ]
