# Generated by Django 4.1.7 on 2023-04-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_schedule_schedule_date_schedule_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
